### ISSUE TITLE
Build out OPAT website

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#153]
- [x] Add content to the OPAT website (remove boilerplate).
- [x] Add roadmap to the site.

Work will be done here
https://github.com/GSA/opat-website

**Comment by danid123** [comment]
@mgifford I think this is a pretty good option for showing how the technology is helpful as a replacement hero image.
https://disabilityin.org/wp-content/uploads/2019/07/JORD1809_WM-1.jpg

**Comment by mgifford** [comment]
Ok, I like that one too.

**Comment by mgifford** [comment]
This is the image I used above.

![DisabilityIN stock photo hero image cropped](https://user-images.githubusercontent.com/116832/148834623-428e2097-7711-4197-a1db-e7ad3fa72e93.jpg)

**Comment by bruce-usab** [comment]
Nice!  Where did that photo come from?  I am pretty sure that is is [Claudia Gordon](https://www.google.com/search?q=%22claudia+gordon%22) and I am confident she will be pleased!

**Comment by mgifford** [comment]
Wow. They really should add profiles to who these people are. I never heard of her before  https://en.wikipedia.org/wiki/Claudia_L._Gordon

These are stock photos from the great folks at https://disabilityin.org/resource/disability-stock-photography/

There are a few other places to get great stock photos of people with disabilities too. It is starting to get easier to find respectful images of people who actually have disabilities (rather than actors in a chair).

Thanks @bruce-usab
