### ISSUE TITLE
Make Validation an Image

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#299]
Presently we have something like:

### Validation:

Valid!

But it would be way cooler to just have:

<img width="1435" alt="Screen Shot of header of editor with validator checkmark" src="https://user-images.githubusercontent.com/116832/151606370-ecdb1377-bdfa-452f-8f6b-722522706d56.png">

Obviously this would semantically have alt text to make it clear that this is a "Valid OpenACR File"

But that would be a clearer message.

We might also need a "Failed OCR Validation" image.

Could use or modify something like this:
https://pixabay.com/vectors/verified-star-valid-featured-badge-6534504/

**Comment by danid123** [comment]
Instead of making it an image I think we should make it look more like USWDS guidelines and make it an alert. This would also remove the Validation section from the HTML.

![Editor - valid report](https://user-images.githubusercontent.com/4855793/153269915-1f823100-b9e3-45b0-94d2-3c6a325b6f04.png)
![Editor - invalid report](https://user-images.githubusercontent.com/4855793/153269947-9f5aa49e-ac33-4c4a-9b68-bd57fdbc6a99.png)

The symbols used in the alert:
![icon-error](https://user-images.githubusercontent.com/4855793/153270608-22cf5292-dc6c-4e67-9ccc-f12824f95df9.svg)
![icon-check_circle](https://user-images.githubusercontent.com/4855793/153270612-ea7ce22c-6f46-4af1-8a5c-64de99c8c2c5.svg)

The colors are:
- Success (green)
    background-color: #ecf3ec; aka 'green-cool-5'
    border-left-color: #00a91c; aka ''green-cool-40v''
- Error (red)
    background-color: #f4e3db; aka 'red-warm-10'
    border-left-color: #d54309; aka 'red-warm-50v'
    
    I'll create another ticket to make other styling changes.

**Comment by mgifford** [comment]
Looks great.

**Comment by danid123** [comment]
Assigning to @dmundra to implement.

**Comment by danid123** [comment]
@dmundra I know you said that it would be very hard to make an invalid report. Do you have specific examples? Could we make the error message more specific?

**Comment by dmundra** [comment]
@danid123 here is what an example invalid one would look like. In this case I add an invalid option to the level select options:

> ## Validation
> Invalid: data/chapters/success_criteria_level_a/criteria/0/components/0/adherence must have required property 'level'

That invalid message is pointing to the error in the YAML file. Since we haven't gotten a way to add invalid data in the editor I haven't translated that to the 'editor location'.

**Comment by dmundra** [comment]
Followed this https://designsystem.digital.gov/components/alert/ and should be able to share an implementation soon.
